---
language: go
sudo: required
go: "master"

before_install:
  - sudo apt-get -qq update
  - sudo apt-get install -y git qemu-kvm qemu-utils qemu-block-extra

install:
  - mkdir -p $GOPATH/src/github.com/hashicorp && cd $_
  - git clone https://github.com/hashicorp/packer.git
  - cd packer
  - make dev
  - cd "$TRAVIS_BUILD_DIR"

script:
  - |
    travis_wait 60 sudo packer build \
        -var 'boot_wait=30s' \
        -var 'post_bootloader_wait=2m' \
        arch-template.json
